services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_usuariosapp
    restart: always
    environment:
      SA_PASSWORD: "Coti@2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_usuariosapp
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_usuariosapp
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  sqlserver_data:
  rabbitmq_data: